---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openobserve
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: openobserve
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ZO_ROOT_USER_EMAIL: "{{ .username }}"
        ZO_ROOT_USER_PASSWORD: "{{ .password }}"
        OPENOBSERVE_AUTH_HEADER: "Basic {{ printf \"%s:%s\" .username .password | b64enc }}"
  dataFrom:
    - extract:
        key: openobserve
