---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tmdb-external
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tmdb 
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        apikey: "{{ .apikey }}"
  dataFrom:
    - extract:
        key: tmdb
