---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  labels:
    app.kubernetes.io/instance: qbittorrent
    app.kubernetes.io/name: qbittorrent
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: replica-block
