#resource "proxmox_cluster_ha_resource" "ha_resource" {
#  id           = "vm:${proxmox_node_virtual_machine.guest.id}"
#  max_relocate = 0
#  max_restart  = 3
#  comment      = "Generated by TF"
#  state        = "started"
#}
