---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux-webhook
  namespace: flux-system
spec:
  parentRefs:
    - kind: ListenerSet
      name: deangalvin-dev-listener-set
      namespace: networking
  hostnames:
    - "flux-webhook.${DOMAIN}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /hook
      backendRefs:
        - name: webhook-receiver
          port: 80
