---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate-webhook-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: konflate-webhook-token-secret
    template:
      data:
        KONFLATE_WEBHOOK_SECRET: "{{ .webhook_secret }}"
        KONFLATE_APP_CLIENT_ID: "{{ .client_id }}"
        KONFLATE_APP_PRIVATE_KEY: '{{ index . "privatekey.pem" }}'
  dataFrom:
    - extract:
        key: konflate
    - extract:
        key: github-bot
