---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main
spec:
  gatewayClassName: istio
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: "10.1.21.20"
    labels:
      service.istio.io/canonical-name: istio-gateway
  listeners: []
