---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
spec:
  interval: 30m
  timeout: 30m
  chart:
    spec:
      chart: tempo
      version: 1.24.4
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    tempo:
      retention: 168h
      metricsGenerator:
        enabled: true
        remoteWriteUrl: http://kube-prometheus-stack-prometheus:9090/api/v1/write
        processor:
          local_blocks:
            flush_to_storage: true
      overrides:
        defaults:
          metrics_generator:
            processors:
              - service-graphs
              - span-metrics
              - local-blocks
    persistence:
      enabled: true
      size: 100Gi
      storageClassName: replica-block
