---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ec-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ec-cephfs
  resources:
    requests:
      storage: "150Ti"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: replica-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: replica-cephfs
  volumeName: replica-media-ceph
  resources:
    requests:
      storage: "100Ti"
