{
 "title": "Server Hardware",
 "tags": [
  "homelab",
  "tv",
  "servers",
  "hardware"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Challenger",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(redfish_chassis_temperature_celsius{job=\"redfish-exporter-challenger\",sensor_id=~\".*CPU.*Temp\"})"
    }
   ]
  },
  {
   "title": "Galaxy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(redfish_chassis_temperature_celsius{job=\"redfish-exporter-galaxy\",sensor_id=~\".*CPU.*Temp\"})"
    }
   ]
  },
  {
   "title": "Yamato",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(redfish_chassis_temperature_celsius{job=\"redfish-exporter-yamato\",sensor_id=~\".*CPU.*Temp\"})"
    }
   ]
  },
  {
   "title": "CPU Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "redfish_chassis_temperature_celsius{sensor_id=~\".*CPU.*Temp\"}",
     "legendFormat": "{{job}} - {{sensor_id}}"
    }
   ]
  },
  {
   "title": "System Board Exhaust Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "redfish_chassis_temperature_celsius{sensor_id=~\".*SystemBoardExhaustTemp\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Fan Speeds (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "redfish_chassis_fan_rpm_percentage",
     "legendFormat": "{{job}} - {{fan_name}}"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "redfish_chassis_power_average_consumed_watts",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}