---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector
spec:
  chartRef:
    kind: OCIRepository
    name: otel-collector
  interval: 30m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    mode: deployment
    replicaCount: 2
    image:
      repository: otel/opentelemetry-collector-k8s
    presets:
      kubernetesAttributes:
        enabled: true
    extraEnvsFrom:
      - secretRef:
          name: openobserve
    ports:
      jaeger-compact:
        enabled: false
      jaeger-thrift:
        enabled: false
      jaeger-grpc:
        enabled: false
      zipkin:
        enabled: false
    config:
      receivers:
        jaeger: null
        zipkin: null
        prometheus: null
      exporters:
        otlp:
          endpoint: tempo:4317
          tls:
            insecure: true
        otlphttp/openobserve:
          endpoint: http://openobserve:5080/api/default
          headers:
            Authorization: $${env:OPENOBSERVE_AUTH_HEADER}
            stream-name: default
      processors:
        batch:
          timeout: 5s
          send_batch_size: 1024
      service:
        pipelines:
          logs: null
          metrics: null
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp, otlphttp/openobserve]
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        memory: 512Mi
