---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-config
  namespace: ghost
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/name: ghost-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ceph-rbd
