---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-config
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/name: ghost-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ceph-rbd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-mariadb
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/name: ghost-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ceph-rbd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-config-tmp
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/name: ghost-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: replica-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/name: ghost-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: replica-block
