---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/name: ghost
  name: ghost-public
spec:
  parentRefs:
    - kind: ListenerSet
      name: subtle-studio-com-listener-set
      namespace: networking
  hostnames:
    - blog.subtle-studio.com
    - www.subtle-studio.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ghost
          port: 2368
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/name: ghost
  name: ghost-apex
spec:
  parentRefs:
    - kind: ListenerSet
      name: subtle-studio-com-listener-set
      namespace: networking
  hostnames:
    - subtle-studio.com
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            hostname: www.subtle-studio.com
            statusCode: 301
