---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
data:
  istio-forward-auth.yaml: |
    version: 1
    metadata:
      name: istio-forward-auth
    entries:
      - id: provider
        model: authentik_providers_proxy.proxyprovider
        identifiers:
          name: istio-forward-auth
        attrs:
          mode: forward_domain
          external_host: https://authentik.deangalvin.dev
          cookie_domain: deangalvin.dev
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      - model: authentik_core.application
        identifiers:
          slug: istio-forward-auth
        attrs:
          name: Istio Forward Auth
          provider: !KeyOf provider
      - model: authentik_outposts.outpost
        identifiers:
          managed: goauthentik.io/outposts/embedded
        attrs:
          providers:
            - !KeyOf provider
