---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./gcs-credentials.yaml
  - ./replication-destination.yaml
  - ./plex-backup.yaml
  - ./volsync/ks.yaml
