---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./gcs-credentials.yaml
  - ./replication-destination.yaml
  - ./volsync/ks.yaml
  - storage/plex
  # Add more storage components here:
  # - storage/jellyfin
  # - storage/sonarr
  # - storage/radarr
