---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-data
  labels:
    app.kubernetes.io/instance: satisfactory
    app.kubernetes.io/name: satisfactory-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: replica-block
