---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-config-tmp
  labels:
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/name: ghost
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: replica-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  labels:
    app.kubernetes.io/instance: ghost-mariadb
    app.kubernetes.io/name: mariadb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: replica-block
